### ISSUE TITLE
"This extension violates the Chrome Web Store policy"

### ISSUE THREAD

**Issue by spookytheripper** [jazzfog/Reload-Images-Browser-Plugin#1]
Hi,

The Plugin is not in the Stores anylonger and it appears that "This extension violates the Chrome Web Store policy."

What is the issue with the Store?

I realize nobody has worked on the project for a long time, but is there any chances that is going to be back on the stores?

Thanks

**Comment by jazzfog** [comment]
Hi, sorry about that.
Few months ago they mailed me that the extension "Having [excessive and / or irrelevant keywords] in the item's description".
I did not have chance to look into it so they've deleted it.
I will check to see if it's possible to restore it...

**Comment by spookytheripper** [comment]
Hey Pavel,
Thank you for your replay (and obviously for creating the plugin), i hope it's not too much of an hassle to fix it.
Cheers

**Comment by jazzfog** [comment]
So I've looked into it and it looks like the real reason why they took don the extension is "Short description is repeated in extension’s description" 🤦‍♂️ IMO not good enough reason to take down someone's work...

Anyways, I had to replace a "long description" that was perfectly good and captured the essence of the extension with some longer text and a bunch of other information they now require to submit the extension... now will have to wait till they make the decision...

**Comment by spookytheripper** [comment]
Ugh, silly google.

Thank you so much for looking into it.

**Comment by jazzfog** [comment]
Looks like the extension is back in store.
Thanks for bringing my attention to the issue!
